const express = require("express");
const multer = require("multer");
const path = require("path");
const fs = require("fs");
const crypto = require("crypto");
const Database = require("better-sqlite3");

const app = express();
const PORT = process.env.PORT || 3000;
const ADMIN_USERNAME = String(process.env.ADMIN_USERNAME || "test").trim();
const ADMIN_PASSWORD_HASH = String(process.env.ADMIN_PASSWORD_HASH || "feeea7ab1ad088b71099337051d24f75ec0e71d3f90045a163359c761512ccf0").trim();
const dataDir = path.join(__dirname, "data");
const uploadDir = path.join(__dirname, "uploads");
const publicDir = path.join(__dirname, "public");
fs.mkdirSync(dataDir, { recursive: true });
fs.mkdirSync(uploadDir, { recursive: true });
const db = new Database(path.join(dataDir, "miiverse.sqlite"));
db.pragma("journal_mode = WAL");
db.pragma("foreign_keys = ON");

db.exec(`
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, avatar TEXT, banned INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS posts (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, text TEXT NOT NULL, image TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS post_yeahs (post_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY (post_id,user_id), FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS warnings (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, admin_user_id INTEGER NOT NULL, reason TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (admin_user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS replies (id INTEGER PRIMARY KEY AUTOINCREMENT, post_id INTEGER NOT NULL, user_id INTEGER NOT NULL, text TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, actor_id INTEGER, type TEXT NOT NULL, post_id INTEGER, reply_id INTEGER, message TEXT NOT NULL, read INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE, FOREIGN KEY (reply_id) REFERENCES replies(id) ON DELETE CASCADE);
`);
function ensureColumn(table,column,definition){const cols=db.prepare(`PRAGMA table_info(${table})`).all();if(!cols.some(x=>x.name===column))db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);}
ensureColumn("users","banned","INTEGER NOT NULL DEFAULT 0"); ensureColumn("posts","image","TEXT");
app.use(express.json({limit:"100kb"})); app.use(express.urlencoded({extended:true})); app.use(express.static(publicDir)); app.use("/uploads",express.static(uploadDir));
app.get("/",(req,res)=>res.sendFile(path.join(publicDir,"index.html")));
const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,uploadDir),filename:(req,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase()||".png";cb(null,`${Date.now()}-${Math.random().toString(36).slice(2)}${ext}`);}});
const upload=multer({storage,limits:{fileSize:4*1024*1024},fileFilter:(req,file,cb)=>{const allowed=["image/png","image/jpeg","image/webp","image/gif"];cb(null,allowed.includes(file.mimetype)?true:new Error("Only PNG, JPEG, WebP and GIF images are allowed."));}});
function getUser(id){return db.prepare("SELECT id,name,avatar,banned,created_at FROM users WHERE id=?").get(id);}
function isAdmin(id){const u=getUser(id);return Boolean(u&&u.name.toLowerCase()===ADMIN_USERNAME.toLowerCase());}
function passwordMatches(password){return crypto.createHash("sha256").update(String(password||"")).digest("hex")===ADMIN_PASSWORD_HASH;}
function requireAdmin(id,req,res){if(!Number.isInteger(id)||id<=0||!isAdmin(id)||!passwordMatches(req.headers["x-admin-password"]||"")){res.status(403).json({error:"Admin access required."});return false;}return true;}
function addNotification(userId,actorId,type,postId,replyId,message){if(!userId||userId===actorId)return;db.prepare("INSERT INTO notifications (user_id,actor_id,type,post_id,reply_id,message) VALUES (?,?,?,?,?,?)").run(userId,actorId,type,postId||null,replyId||null,message);}

app.post("/api/users",upload.single("avatar"),(req,res)=>{try{const name=String(req.body.name||"").trim().slice(0,24);if(!name)return res.status(400).json({error:"A name is required."});if(db.prepare("SELECT id FROM users WHERE name=? COLLATE NOCASE").get(name))return res.status(409).json({error:"That GreenTendo name is already in use. Try logging in instead."});const avatar=req.file?`/uploads/${req.file.filename}`:null;const r=db.prepare("INSERT INTO users (name,avatar) VALUES (?,?)").run(name,avatar);res.json({id:Number(r.lastInsertRowid),name,avatar,banned:0});}catch(e){console.error(e);res.status(500).json({error:"Could not create user."});}});
app.post("/api/login",(req,res)=>{try{const name=String(req.body.name||"").trim().slice(0,24);if(!name)return res.status(400).json({error:"Enter your GreenTendo name."});const matches=db.prepare("SELECT id,name,avatar,banned FROM users WHERE name=? COLLATE NOCASE").all(name);if(!matches.length)return res.status(404).json({error:"No GreenTendo account was found with that name."});if(matches.length>1)return res.status(409).json({error:"More than one old account has that name. This name cannot be used for passwordless login."});if(matches[0].banned)return res.status(403).json({error:"This GreenTendo account is banned."});res.json(matches[0]);}catch(e){console.error(e);res.status(500).json({error:"Could not log in."});}});
app.get("/api/users/:id",(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id)||id<=0)return res.status(400).json({error:"Invalid user ID."});const u=getUser(id);if(!u)return res.status(404).json({error:"User not found."});res.json(u);});
app.get("/api/users/:id/warnings",(req,res)=>{const id=Number(req.params.id),requester=Number(req.query.requesterId);if(!Number.isInteger(id)||id<=0)return res.status(400).json({error:"Invalid user ID."});if(id!==requester&&!isAdmin(requester))return res.status(403).json({error:"You can only view your own warnings."});res.json(db.prepare("SELECT warnings.id,warnings.reason,warnings.created_at,admins.name AS admin_name FROM warnings JOIN users AS admins ON admins.id=warnings.admin_user_id WHERE warnings.user_id=? ORDER BY warnings.id DESC").all(id));});
app.post("/api/admin/login",(req,res)=>{const id=Number(req.body.userId);if(!Number.isInteger(id)||!isAdmin(id))return res.status(403).json({error:"Admin access required."});if(!passwordMatches(req.body.password))return res.status(401).json({error:"Incorrect admin password."});res.json({admin:true});});
app.get("/api/admin/status",(req,res)=>{const id=Number(req.query.userId);res.json({admin:Number.isInteger(id)&&id>0&&isAdmin(id)});});
app.get("/api/admin/stats",(req,res)=>{const id=Number(req.query.userId);if(!requireAdmin(id,req,res))return;res.json({users:db.prepare("SELECT COUNT(*) count FROM users").get().count,posts:db.prepare("SELECT COUNT(*) count FROM posts").get().count,yeahs:db.prepare("SELECT COUNT(*) count FROM post_yeahs").get().count,warnings:db.prepare("SELECT COUNT(*) count FROM warnings").get().count,banned:db.prepare("SELECT COUNT(*) count FROM users WHERE banned=1").get().count});});
app.get("/api/admin/users",(req,res)=>{const id=Number(req.query.userId);if(!requireAdmin(id,req,res))return;res.json(db.prepare("SELECT users.id,users.name,users.avatar,users.banned,users.created_at,COUNT(warnings.id) warning_count FROM users LEFT JOIN warnings ON warnings.user_id=users.id GROUP BY users.id ORDER BY users.id DESC").all());});
app.get("/api/admin/posts",(req,res)=>{const id=Number(req.query.userId);if(!requireAdmin(id,req,res))return;res.json(db.prepare("SELECT posts.id,posts.text,posts.image,posts.created_at,users.id user_id,users.name,(SELECT COUNT(*) FROM post_yeahs WHERE post_yeahs.post_id=posts.id) yeahs FROM posts JOIN users ON users.id=posts.user_id ORDER BY posts.id DESC LIMIT 200").all());});
app.delete("/api/admin/posts/:id",(req,res)=>{const aid=Number(req.body.userId),pid=Number(req.params.id);if(!requireAdmin(aid,req,res))return;const p=db.prepare("SELECT image FROM posts WHERE id=?").get(pid);if(!p)return res.status(404).json({error:"Post not found."});db.prepare("DELETE FROM posts WHERE id=?").run(pid);if(p.image&&p.image.startsWith("/uploads/")){const f=path.join(uploadDir,path.basename(p.image));if(fs.existsSync(f))fs.unlinkSync(f);}res.json({deleted:true});});
app.post("/api/admin/warnings",(req,res)=>{const aid=Number(req.body.adminId),uid=Number(req.body.userId),reason=String(req.body.reason||"").trim().slice(0,500);if(!requireAdmin(aid,req,res))return;if(!Number.isInteger(uid)||uid<=0)return res.status(400).json({error:"Invalid user ID."});if(!reason)return res.status(400).json({error:"A warning reason is required."});if(uid===aid)return res.status(400).json({error:"You cannot warn the admin account."});if(!getUser(uid))return res.status(404).json({error:"User not found."});db.prepare("INSERT INTO warnings (user_id,admin_user_id,reason) VALUES (?,?,?)").run(uid,aid,reason);const count=db.prepare("SELECT COUNT(*) count FROM warnings WHERE user_id=?").get(uid).count;res.json({warned:true,warningCount:count});});
app.post("/api/admin/ban",(req,res)=>{const aid=Number(req.body.adminId),uid=Number(req.body.userId);if(!requireAdmin(aid,req,res))return;if(uid===aid)return res.status(400).json({error:"You cannot ban the admin account."});if(!getUser(uid))return res.status(404).json({error:"User not found."});db.prepare("UPDATE users SET banned=1 WHERE id=?").run(uid);res.json({banned:true});});
app.post("/api/admin/unban",(req,res)=>{const aid=Number(req.body.adminId),uid=Number(req.body.userId);if(!requireAdmin(aid,req,res))return;if(!getUser(uid))return res.status(404).json({error:"User not found."});db.prepare("UPDATE users SET banned=0 WHERE id=?").run(uid);res.json({banned:false});});
app.delete("/api/admin/users/:id",(req,res)=>{const aid=Number(req.body.userId),uid=Number(req.params.id);if(!requireAdmin(aid,req,res))return;if(uid===aid)return res.status(400).json({error:"You cannot delete the admin account."});const u=getUser(uid);if(!u)return res.status(404).json({error:"User not found."});const files=[u.avatar,...db.prepare("SELECT image FROM posts WHERE user_id=? AND image IS NOT NULL").all(uid).map(x=>x.image)].filter(Boolean);db.transaction(()=>{db.prepare("DELETE FROM post_yeahs WHERE user_id=? OR post_id IN (SELECT id FROM posts WHERE user_id=?)").run(uid,uid);db.prepare("DELETE FROM posts WHERE user_id=?").run(uid);db.prepare("DELETE FROM warnings WHERE user_id=? OR admin_user_id=?").run(uid,uid);db.prepare("DELETE FROM users WHERE id=?").run(uid);})();for(const file of files){if(file.startsWith("/uploads/")){const f=path.join(uploadDir,path.basename(file));if(fs.existsSync(f))fs.unlinkSync(f);}}res.json({deleted:true});});

app.get("/api/posts",(req,res)=>{try{const uid=Number(req.query.userId)||0;const posts=db.prepare("SELECT posts.id,posts.text,posts.image,posts.created_at,users.id user_id,users.name,users.avatar,(SELECT COUNT(*) FROM post_yeahs WHERE post_yeahs.post_id=posts.id) yeahs,CASE WHEN EXISTS(SELECT 1 FROM post_yeahs WHERE post_yeahs.post_id=posts.id AND post_yeahs.user_id=?) THEN 1 ELSE 0 END yeahed FROM posts JOIN users ON users.id=posts.user_id WHERE users.banned=0 ORDER BY posts.id DESC LIMIT 100").all(uid);res.json(posts);}catch(e){console.error(e);res.status(500).json({error:"Could not load posts."});}});
app.post("/api/posts",upload.single("image"),(req,res)=>{try{const uid=Number(req.body.userId),text=String(req.body.text||"").trim().slice(0,500);if(!Number.isInteger(uid)||uid<=0)return res.status(400).json({error:"Invalid user ID."});if(!text&&!req.file)return res.status(400).json({error:"Post cannot be empty."});const u=getUser(uid);if(!u)return res.status(404).json({error:"User not found."});if(u.banned)return res.status(403).json({error:"This account is banned."});const image=req.file?`/uploads/${req.file.filename}`:null;const r=db.prepare("INSERT INTO posts (user_id,text,image) VALUES (?,?,?)").run(uid,text,image);res.json({id:Number(r.lastInsertRowid)});}catch(e){console.error(e);res.status(500).json({error:"Could not create post."});}});

app.get("/api/posts/:id/replies",(req,res)=>{const pid=Number(req.params.id);if(!Number.isInteger(pid)||pid<=0)return res.status(400).json({error:"Invalid post ID."});if(!db.prepare("SELECT id FROM posts WHERE id=?").get(pid))return res.status(404).json({error:"Post not found."});res.json(db.prepare("SELECT replies.id,replies.post_id,replies.user_id,replies.text,replies.created_at,users.name,users.avatar FROM replies JOIN users ON users.id=replies.user_id WHERE replies.post_id=? AND users.banned=0 ORDER BY replies.id ASC").all(pid));});
app.post("/api/posts/:id/replies",(req,res)=>{try{const pid=Number(req.params.id),uid=Number(req.body.userId),text=String(req.body.text||"").trim().slice(0,500);if(!Number.isInteger(pid)||!Number.isInteger(uid)||uid<=0)return res.status(400).json({error:"Invalid ID."});if(!text)return res.status(400).json({error:"Reply cannot be empty."});const u=getUser(uid);if(!u)return res.status(404).json({error:"User not found."});if(u.banned)return res.status(403).json({error:"This account is banned."});const p=db.prepare("SELECT id,user_id FROM posts WHERE id=?").get(pid);if(!p)return res.status(404).json({error:"Post not found."});const r=db.prepare("INSERT INTO replies (post_id,user_id,text) VALUES (?,?,?)").run(pid,uid,text);addNotification(p.user_id,uid,"reply",pid,Number(r.lastInsertRowid),`${u.name} replied to your post.`);res.json({id:Number(r.lastInsertRowid)});}catch(e){console.error(e);res.status(500).json({error:"Could not create reply."});}});
app.post("/api/posts/:id/yeah",(req,res)=>{try{const pid=Number(req.params.id),uid=Number(req.body.userId);if(!Number.isInteger(pid)||pid<=0||!Number.isInteger(uid)||uid<=0)return res.status(400).json({error:"Invalid ID."});const u=getUser(uid);if(!u)return res.status(404).json({error:"User not found."});if(u.banned)return res.status(403).json({error:"This account is banned."});const p=db.prepare("SELECT id,user_id FROM posts WHERE id=?").get(pid);if(!p)return res.status(404).json({error:"Post not found."});const existing=db.prepare("SELECT post_id FROM post_yeahs WHERE post_id=? AND user_id=?").get(pid,uid);if(existing){db.prepare("DELETE FROM post_yeahs WHERE post_id=? AND user_id=?").run(pid,uid);return res.json({yeahed:false,yeahs:db.prepare("SELECT COUNT(*) yeahs FROM post_yeahs WHERE post_id=?").get(pid).yeahs});}db.prepare("INSERT INTO post_yeahs (post_id,user_id) VALUES (?,?)").run(pid,uid);addNotification(p.user_id,uid,"yeah",pid,null,`${u.name} Yeah'd your post.`);res.json({yeahed:true,yeahs:db.prepare("SELECT COUNT(*) yeahs FROM post_yeahs WHERE post_id=?").get(pid).yeahs});}catch(e){console.error(e);res.status(500).json({error:"Could not change Yeah status."});}});

app.get("/api/notifications",(req,res)=>{const uid=Number(req.query.userId);if(!Number.isInteger(uid)||uid<=0)return res.status(400).json({error:"Invalid user ID."});if(!getUser(uid))return res.status(404).json({error:"User not found."});const notifications=db.prepare("SELECT notifications.id,notifications.type,notifications.post_id,notifications.reply_id,notifications.message,notifications.read,notifications.created_at,actors.name actor_name,actors.avatar actor_avatar FROM notifications LEFT JOIN users actors ON actors.id=notifications.actor_id WHERE notifications.user_id=? ORDER BY notifications.id DESC LIMIT 100").all(uid);const unread=db.prepare("SELECT COUNT(*) count FROM notifications WHERE user_id=? AND read=0").get(uid).count;res.json({notifications,unread});});
app.post("/api/notifications/read",(req,res)=>{const uid=Number(req.body.userId);if(!Number.isInteger(uid)||uid<=0)return res.status(400).json({error:"Invalid user ID."});if(!getUser(uid))return res.status(404).json({error:"User not found."});if(req.body.id){db.prepare("UPDATE notifications SET read=1 WHERE id=? AND user_id=?").run(Number(req.body.id),uid);}else{db.prepare("UPDATE notifications SET read=1 WHERE user_id=?").run(uid);}res.json({ok:true});});

app.use((error,req,res,next)=>{console.error(error);if(error instanceof multer.MulterError)return res.status(400).json({error:"Image upload failed."});if(error)return res.status(400).json({error:error.message||"Something went wrong."});next();});
app.listen(PORT,()=>{console.log(`Greenverse running on port ${PORT}`);console.log(`Public directory: ${publicDir}`);console.log(`Index exists: ${fs.existsSync(path.join(publicDir,"index.html"))}`);});